version: "3" #TODO: Update this/check what I should set to.

services:
  postgres:
    build:
      context: .
      dockerfile: ./postgres/pgvector.Dockerfile
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./postgres/init_pgvector.sql:/docker-entrypoint-initdb.d/init_pgvector.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
  ollama:
    container_name: ollama_cat
    image: ollama/ollama:latest
    command: ollama serve
    volumes:
      - ./ollama:/root/.ollama
    expose:
      - "11434:11434"
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    deploy:
      resources:
        limits:
          memory: 5g
